version: 2
jobs:
  build:
    working_directory: /go/src/github.com/bcates277/invoicer-chapter2
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Setup environment
          command: |
            if [ "${THE_CIRCLE_PROJECT_USERNAME}" == "Securing-DevOps" ]; then
              dr="securingdevops"
            else
              dr=${DOCKER_USER}
            fi
            cat >> $BASH_ENV <<EOF
            export DOCKER_REPO="${dr}"
