version: 2.1

jobs:
  build:
    working_directory: /go/src/github.com/bcates277/invoicer-chapter2
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Setup environment
          command: |
            gb="/src/github.com/${THE_CIRCLE_PROJECT_USERNAME}";
            if [ ${THE_CIRCLE_PROJECT_USERNAME} == 'Securing-DevOps' ]; then
              dr="securingdevops"
            else
              dr=$DOCKER_USER
            fi
            cat >> $BASH_ENV \<<EOF
            export GOPATH_HEAD="$(echo ${GOPATH}|cut -d ':' -f 1)"
            export GOPATH_BASE="$(echo ${GOPATH}|cut -d ':' -f 1)${gb}"
            export DOCKER_REPO="$dr"
            EOF

      - run: mkdir -p "${GOPATH_BASE}"
      - run: mkdir -p "${GOPATH_HEAD}/bin"

      - run:
          name: Testing application
          command: |
            go test github.com/${THE_CIRCLE_PROJECT_USERNAME}/${THE_CIRCLE_PROJECT_REPONAME}

      - run:
          name: Build Docker Image
          command: |
            docker build -t ${DOCKER_REPO}/${THE_CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1} .

      - run:
          name: Push Docker Image (only on master)
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
              docker push ${DOCKER_REPO}/${THE_CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}
            fi

      - run:
          name: Install Trivy
          command: |
            sudo apt-get update && sudo apt-get install -y curl
            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin

      - run:
          name: Trivy Summary Scan
          command: |
            trivy image --exit-code 0 --no-progress --severity HIGH,CRITICAL ${DOCKER_REPO}/${THE_CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}

      - run:
          name: Trivy JSON Report
          command: |
            mkdir -p /tmp/trivy
            trivy image --format json --output /tmp/trivy/trivy-report.json ${DOCKER_REPO}/${THE_CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}

      - run:
          name: Confirm Report Exists
          command: |
            echo "Contents of /tmp/trivy:"
            ls -lah /tmp/trivy
            cat /tmp/trivy/trivy-report.json || echo "No report found."

      - store_artifacts:
          path: /tmp/trivy/trivy-report.json
          destination: trivy-report

workflows:
  version: 2
  build_and_scan:
    jobs:
      - build
