version: 2
jobs:
  build:
    working_directory: /go/src/github.com/bcates277/invoicer-chapter2
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Setup environment
          command: |
            if [ "${THE_CIRCLE_PROJECT_USERNAME}" == "Securing-DevOps" ]; then
              dr="securingdevops"
            else
              dr=${DOCKER_USER}
            fi
            cat >> $BASH_ENV <<EOF
            export DOCKER_REPO="${dr}"
            export IMAGE_TAG="${dr}/${THE_CIRCLE_PROJECT_REPONAME}:latest"
            EOF

      - run:
          name: Testing application
          command: |
            go test github.com/${THE_CIRCLE_PROJECT_USERNAME}/${THE_CIRCLE_PROJECT_REPONAME}

      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
              go install --ldflags '-extldflags "-static"' \
                github.com/${THE_CIRCLE_PROJECT_USERNAME}/${THE_CIRCLE_PROJECT_REPONAME}
              mkdir bin
              cp "$GOPATH/bin/${THE_CIRCLE_PROJECT_REPONAME}" bin/invoicer
              docker build -t ${IMAGE_TAG} .

              # Start app container
              docker run -d -p 8080:8080 --name invoicer-container ${IMAGE_TAG}
              sleep 10 # Wait for app to become available

              # Run ZAP scan with more detailed logging
              mkdir -p zap-reports
              docker pull ghcr.io/zaproxy/zaproxy:stable
              docker run --rm \
                --network host \
                -v $(pwd)/zap-reports:/zap/wrk \
                ghcr.io/zaproxy/zaproxy:stable \
                zap.sh -cmd -quickurl http://localhost:8080 \
                -quickprogress \
                -quickout /zap/wrk/zap-report.html \
                -addoninstall pscanrulesBeta \
                -verbose || true

              # Check ZAP logs for any errors or issues
              docker logs $(docker ps -q -f name=zaproxy) || echo "No logs found for ZAP container"

              # Check the contents of /zap/wrk to confirm the report exists
              docker run --rm \
                -v $(pwd)/zap-reports:/zap/wrk \
                ghcr.io/zaproxy/zaproxy:stable \
                ls -l /zap/wrk || echo "No report found in container"

              # Clean up
              docker stop invoicer-container
              docker rm invoicer-container

              # Push image
              docker push ${IMAGE_TAG}
            fi

      - run:
          name: Check for ZAP report
          command: ls -l zap-reports || echo "Report not found"

      - store_artifacts:
          path: /go/src/github.com/bcates277/invoicer-chapter2/zap-reports/zap-report.html
          destination: zap-report
