version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.18
    working_directory: /home/circleci/project

    steps:
      - checkout

      - run:
          name: Create directories with proper permissions
          command: |
            sudo mkdir -p /go/src/github.com/bcates277/invoicer-chapter2
            sudo chown -R circleci:circleci /go

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Setup environment
          command: |
            gb="/src/github.com/${THE_CIRCLE_PROJECT_USERNAME}"
            if [ "${THE_CIRCLE_PROJECT_USERNAME}" == "Securing-DevOps" ]; then
              dr="securingdevops"
            else
              dr=$DOCKER_USER
            fi
            cat >> $BASH_ENV \<<EOF
            export GOPATH_HEAD="$(echo ${GOPATH} | cut -d ':' -f 1)"
            export GOPATH_BASE="$(echo ${GOPATH} | cut -d ':' -f 1)${gb}"
            export DOCKER_REPO="$dr"
            EOF

      - run:
          name: Make directories
          command: |
            mkdir -p "${GOPATH_BASE}"
            mkdir -p "${GOPATH_HEAD}/bin"

      - run:
          name: Testing application
          command: |
            go test github.com/${THE_CIRCLE_PROJECT_USERNAME}/${THE_CIRCLE_PROJECT_REPONAME}

      - run:
          name: Build Go binary
          command: |
            go install --ldflags '-extldflags "-static"' \
              github.com/${THE_CIRCLE_PROJECT_USERNAME}/${THE_CIRCLE_PROJECT_REPONAME}
            mkdir -p bin
            cp "$GOPATH_HEAD/bin/${THE_CIRCLE_PROJECT_REPONAME}" bin/invoicer

      - run:
          name: Build Docker Image
          command: |
            docker build -t ${DOCKER_REPO}/${THE_CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1} .

      - run:
          name: Push Docker Image (only on master)
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
              docker push ${DOCKER_REPO}/${THE_CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}
            fi

      - run:
          name: Create Docker network
          command: |
            docker network create invoicer-net

      - run:
          name: Start Invoicer App (Docker)
          command: |
            docker run -d --name invoicer-app --network invoicer-net -p 8080:8080 ${DOCKER_REPO}/${THE_CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}

      - run:
          name: Wait for App to Start
          command: |
            for i in {1..10}; do
              if curl -s http://localhost:8080/health || curl -s http://localhost:8080; then
                echo "App is up!"
                break
              fi
              echo "Waiting for app..."
              sleep 5
            done

      - run:
          name: Fix permissions for ZAP working directory
          command: |
            sudo mkdir -p /zap/wrk
            sudo chown -R circleci:circleci /zap

      - run:
          name: Install ZAP
          command: |
            docker pull zaproxy/zap-stable

      - run:
          name: Run ZAP scan
          command: |
            docker run --rm \
              --network invoicer-net \
              -v /home/circleci/project:/zap/wrk:rw \
              zaproxy/zap-stable zap-baseline.py -t http://invoicer-app:8080

workflows:
  version: 2
  release:
    jobs:
      - build
